### ISSUE TITLE
What is breaker inutil functions()  ? undefined

### ISSUE THREAD

**Issue by iisfaq** [gdandar/Knockout-Parsley#3]
var util = (function(){
		return {
			nativeForEach: Array.prototype.forEach,

			isArray: Array.isArray || function(obj) {
				return toString.call(obj) == '[object Array]';
			},

			each: function(obj, iterator, context) {
				if (obj === null) return;
				if (util.nativeForEach && obj.forEach === util.nativeForEach) {
					obj.forEach(iterator, context);
				} else if ( util.isArray(obj) ) {
					for (var i = 0, l = obj.length; i < l; i++) {
						if (iterator.call(context, obj[i], i, obj) === breaker) return;
					}
				} else {
					for (var key in obj) {
						if (iterator.call(context, obj[key], key, obj) === breaker) return;
					}
				}
			}
		};
	}());

In the code above what is breaker?

It is not defined anywhere and IE 8 breaks with this code.

Chris

**Comment by gdandar** [comment]
@iisfaq Thanks for the report Chris! Fixed in a59c878a9f7610335b627e3393e6558a705c0e26
